apiVersion: datacatalog.gcp.upbound.io/v1beta2
kind: TagTemplate
metadata:
  name: basictagtemplate
spec:
  forProvider:
    displayName: Demo Tag Template
    fields:
      - displayName: Source of data asset
        fieldId: source
        isRequired: true
        type:
          primitiveType: STRING
      - displayName: Number of rows in the data asset
        fieldId: num_rows
        type:
          primitiveType: DOUBLE
      - displayName: PII type
        fieldId: pii_type
        type:
          enumType:
            allowedValues:
              - displayName: EMAIL
              - displayName: SOCIAL SECURITY NUMBER
              - displayName: NONE
    forceDelete: true
    region: us-central1